### ISSUE TITLE
Variable for redis-server service name?

### ISSUE THREAD

**Issue by rawtaz** [Mayeu/ansible-playbook-sensu#10]
Hi,

I installed this role along with the `DavidWittman.ansible-redis` (and your RabbitMQ role), but hit the fact that this role, in `files/sensu-api` has a dependency on the service name of redis being `redis-server`, while that other role makes it be `redis_{{port}}`.

Im wondering if it would perhaps make sense to be able to configure the name to expect for the redis service? So that it's not hard-coded to `redis-server` but can be something configured to be else.

**Comment by Mayeu** [comment]
Thank you for your contribution.

Sadly, and has you may have guessed, I don't use this project anymore, nor did I have the time to continue to maintain it.

You can now find an official playbook maintained at [sensu/sensu-ansible](https://github.com/sensu/sensu-ansible).

Wishing you the best, and a gajillion more contribution in your lifetime  :pray::sparkles:
