### ISSUE TITLE
On debian the patched init script force a server to run rabbitmq

### ISSUE THREAD

**Issue by Mayeu** [Mayeu/ansible-playbook-sensu#23]
Currently, the patched init script force a sensu server to run rabbitmq on it, otherwise it won't start. This is dumb and a better way of handling service ordering should be found.

Api & server depend on the fact that a Redis server and a Rabbitmq server are already running. But maybe on other host, and maybe only one of them on the server host.

Ideally the playbook should be able to detect that by himself.

**Comment by mtpereira** [comment]
I've just fixed that on https://github.com/mtpereira/ansible-playbook-sensu/commit/5f8b1316e2d820eca9f82dc3a297c1b81e299cb1 . However, that branch also has some more changes, like merging your PR #14 and a couple of other fixes. For that reason, I did not open a PR for this. If you'd like me to anyway, just say it. :)

**Comment by Mayeu** [comment]
Hi,

Thank for pointing out this patch! By the time you posted this I already had a working implementation for this, using the `should-stop` command of the [LSBInit script](https://wiki.debian.org/LSBInitScripts/) that perfectly match this weak dependency case. I will push this ASAP.

BTW, I totally missed the fact that we can now uses YAML dictionary instead of Python one in arguments of module! Thank for pointing me this also :)
