### ISSUE TITLE
What is the point of using "sensu_client_hostname" & "sensu_client_address" ?

### ISSUE THREAD

**Issue by Azorr** [Mayeu/ansible-playbook-sensu#26]
Instead of using "ansible_hostname" & "ansible_default_ipv4['address']" ?

Maybe there is something I didnt understood there, but would't it make more sense to have those value generated automatically ?

**Comment by Mayeu** [comment]
I'm not sure anymore, I may had a use case before but checking where I use the playbook I always override those variable with fact variable.

I change the default value to match those, override will still be possible, but default will make sense :)
