### ISSUE TITLE
recursive directory loop

### ISSUE THREAD

**Issue by SydOps** [Mayeu/ansible-playbook-sensu#45]
When grep a key word in the repo, get below error

```
grep: warning: ./vagrant/roles/sensu: recursive directory loop
```

Here is the problem. 

```
cd vagrant/roles
lrwxr-xr-x  1 bill  staff   7  3 Jun 17:50 sensu -> ../../.
```

**Comment by Mayeu** [comment]
Thank you for your contribution.

Sadly, and has you may have guessed, I don't use this project anymore, nor did I have the time to continue to maintain it.

You can now find an official playbook maintained at [sensu/sensu-ansible](https://github.com/sensu/sensu-ansible).

Wishing you the best, and a gajillion more contribution in your lifetime  :pray::sparkles:
